# Generated by Django 5.1.6 on 2025-03-20 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0002_lives_works_remove_page_category_delete_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('institute_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('no_of_courses', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Lives',
        ),
        migrations.DeleteModel(
            name='Works',
        ),
    ]
