# Generated by Django 5.1.6 on 2025-03-20 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0003_institute_delete_lives_delete_works'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
